### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by bhargav-inthezone** [tianweiy/CenterPoint-KITTI#13]
Hi I ran this code in colab after installing all the requirements mentioned in Install.md and followed Getting_started.md
! python /content/CenterPoint-KITTI-main/OpenPCDet/tools/train.py
I am getting this error:

Traceback (most recent call last):
  File "/content/CenterPoint-KITTI-main/OpenPCDet/tools/train.py", line 198, in <module>
    main()
  File "/content/CenterPoint-KITTI-main/OpenPCDet/tools/train.py", line 59, in main
    args, cfg = parse_config()
  File "/content/CenterPoint-KITTI-main/OpenPCDet/tools/train.py", line 48, in parse_config
    cfg_from_yaml_file(args.cfg_file, cfg)
  File "/content/CenterPoint-KITTI-main/OpenPCDet/pcdet/config.py", line 72, in cfg_from_yaml_file
    with open(cfg_file, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ ]

**Comment by tianweiy** [comment]
you need to specify the config path by --cfg_file

**Comment by bhargav-inthezone** [comment]
yeah can you please tell me what arguments you have specified and their values

**Comment by bhargav-inthezone** [comment]
> you need to specify the config path by --cfg_file

yeah can you please tell me what arguments you have specified and their values

**Comment by tianweiy** [comment]
Any cfg in this folder https://github.com/tianweiy/CenterPoint-KITTI/tree/main/tools/cfgs/kitti_models works

**Comment by bhargav-inthezone** [comment]
> Any cfg in this folder https://github.com/tianweiy/CenterPoint-KITTI/tree/main/tools/cfgs/kitti_models works

okay Thanks
