### ISSUE TITLE
what exactly this model is dealing with images? 

### ISSUE THREAD

**Issue by bhargav-inthezone** [tianweiy/CenterPoint-KITTI#17]
Hi I am new to this 3d object detection using lidar, images, calibs ..., So in this model where exactly the fusion of images with point cloud data is happening. I am unable to find the information from the research paper of what this model is dealing with images! I think the model architecture is solely dealing with point cloud data. If I am wrong please let me know. And also please let me know what is the purpose of images while training the data!

**Comment by tianweiy** [comment]
it only works with point cloud. 

There is no usage of images during the training currently but you can do some fusion approaches.

**Comment by bhargav-inthezone** [comment]
> it only works with point cloud.
> 
> There is no usage of images during the training currently but you can do some fusion approaches.
okay thanks
