### ISSUE TITLE
Questions about "map_to_bev" module.

### ISSUE THREAD

**Issue by yaxi333** [tianweiy/CenterPoint-KITTI#18]
Hi, @tianweiy 

As mentioned in the Thesis of CenterPoint: “We rely on a standard 3D backbone that extracts map-view feature representation from Lidar point-clouds.”  But in the code, you introduce the "map_to_BEV" module.  Is BEV the same as the"map-view" you have mentioned?  Or they are different but you just what to do detection in BEV here?

Thanks in advance! :D

**Comment by tianweiy** [comment]
Bev is just map view. The function is from openpcdet so use their own convention.

**Comment by yaxi333** [comment]
OK. Thank you~
