### ISSUE TITLE
one stage model

### ISSUE THREAD

**Issue by HuangVictorAuto** [tianweiy/CenterPoint-KITTI#20]
Hi, Tianwei. Thanks for your great work. I have checked your implementation of CenterPoint model based on PCDet in this repo. The version is one stage centerpoint? When can we get the official two stage model? Or the latest CenterPoint++ model?

Thanks!

**Comment by tianweiy** [comment]
Hi, it is one stage. The two stage doesn't improve much on KITTI so I didn't add this. 

You can find CenterPoint++ for Waymo here https://github.com/tianweiy/CenterPoint/tree/new_release Related pull request https://github.com/tianweiy/CenterPoint/pull/157. 

CenterPoint++ is basically: CenterPoint + multi-frame + smaller model for better speed + an one stage IoU prediction. It is mainly for the Waymo challenge and I don't think they will improve KITTI model much.

**Comment by HuangVictorAuto** [comment]
Thanks for your quick reply! For the detailed implementation of two stage and CenterPoint++, I will check your Waymo repo. Actually, I wonder why the same technik can improve Waymo instead of Kitti. What lies behind this, can you give me some hints?

**Comment by tianweiy** [comment]
The CenterPoint++ doesn't necessarily improve Waymo for number. It is mainly optimized for speed.

Basically, it gets these few components:

1. dynamic voxelization. (this one is faster but the output is the same)

2. multi-frame (KITTI doesn't provide multiple frame)

3. smaller model (this is only optimized for speed and the accuracy is worse)

4. one-stage IoU prediction. This one probably works but it is not novel. People widely use it in the past e.g. https://github.com/Vegeta2020/CIA-SSD

5. two-stage refinement. Not really sure why pure bird-eye view based refinement doesn't work too well on KITTI. On KITTI, it seems that point-based two stage (e.g. PVRCNN) is better

**Comment by HuangVictorAuto** [comment]
Thanks for your shared info! I will close the issue.
