### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement spconv (from pcdet) ERROR: No matching distribution found for spconv`

### ISSUE THREAD

**Issue by rockywind** [tianweiy/CenterPoint-KITTI#23]
When I run the script `pip install pcdet-0.3.0+95b7309-cp37-cp37m-linux_x86_64.whl`. the error is below.
My environment is below:
pytorch1.7.1
cuda11.1
A600

`Processing ./pcdet-0.3.0+95b7309-cp37-cp37m-linux_x86_64.whl
Requirement already satisfied: pyyaml in /home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages (from pcdet==0.3.0+95b7309) (5.4.1)
Requirement already satisfied: numba in /home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages (from pcdet==0.3.0+95b7309) (0.52.0)
Requirement already satisfied: numpy in /home/CN/zizhang.wu/anaconda3/envs/CaDDN/lib/python3.7/site-packages (from pcdet==0.3.0+95b7309) (1.20.1)
ERROR: Could not find a version that satisfies the requirement spconv (from pcdet)
ERROR: No matching distribution found for spconv`

**Comment by tianweiy** [comment]
Hi, you need to first install spconv before installing other libraries.

**Comment by tianweiy** [comment]
see here for instruction https://github.com/tianweiy/CenterPoint-KITTI/blob/main/docs/INSTALL.md

**Comment by rockywind** [comment]
Thanks a lot!
