### ISSUE TITLE
dynamic voxelization vs hard voxelization 

### ISSUE THREAD

**Issue by HuangVictorAuto** [tianweiy/CenterPoint-KITTI#26]
Hi Tianwei, I copied your dynamic voxelization implementation from other repo to adapt to OpenPcdet here. Stangely, I found no speed improments compared to the original hard voxelization by OpenPcdet.

I compare the iter/second, no improvements in speed.
The original hard voxelization was done in dataload stage.
![image](https://user-images.githubusercontent.com/54128861/131471890-85f89cef-4c3b-44d4-a467-057cf9ef20d2.png)

The dynamic voxelization was done in model  VFE stage.
![image](https://user-images.githubusercontent.com/54128861/131471509-c9a5b2e0-9269-44a6-89be-f9eac2b26904.png)

Is it because the original hard voxelization metho already a optimized one?

**Comment by tianweiy** [comment]
Hi,

The speed difference is not too large if we use it during training as we have multiple processing in the data loader which hides latency.

You can measure it at inference time+not using a dataloder (which is the real setting in deployment), it should be slightly faster.

Additionally, the speed difference will be larger for larger number of points (e.g. waymo with three sweep, it is about 400k points vs 40k in kitti)

**Comment by HuangVictorAuto** [comment]
Thanks, I will test it latter.
