### ISSUE TITLE
How to implement a two-stage centerpoint on waymo

### ISSUE THREAD

**Issue by Yzichen** [tianweiy/CenterPoint-KITTI#27]
I implement a two-stage centerpoint use with openpcdet, I can't get a good result. I use the proposal_layer in roi_head to obtain one-stage detection results, (I notice that this is different from yours,  you seem to integrate this process into predict  process in centerhead). But I don’t know the essential difference between the two implements.  Is it the reason for the relevant parameters? such as  nms_pre_max_size=4096,
nms_post_max_size=500 in yours implement. in pcdet,   NMS_PRE_MAXSIZE: 1024, NMS_POST_MAXSIZE: 100. 

Besides, I want to ask a question, Why NMS_POST_MAXSIZE (PVRCNN in waymo) can be set to 100.  What to do if the number of targets in the scene is greater than 100 ?

**Comment by tianweiy** [comment]
> Why NMS_POST_MAXSIZE (PVRCNN in waymo) can be set to 100. What to do if the number of targets in the scene is greater than 100 ?

I agree that NMS_POST_MAXSIZE = 100 seems too small. I don't know why PVRCNN sets it to this number. 

Official implementation for two stage Waymo is at this repo https://github.com/tianweiy/CenterPoint/tree/master/configs/waymo I never tried training with centerpoint on Waymo using pcdet, so I don't have much clues about the difference (in addition to the POST_MAXSIZE stuff). Maybe, you can just try 500 and see? The speed should be almost the same if you only use bev features.

**Comment by Yzichen** [comment]
I still can't get the correct result， my implementation should be problematic. If you have time, I hope you can provide the realization
on waymo using pcdet! Thank you very much! I will continue to look for the problems that I realize, maybe I don't have enough understanding of the paper.

**Comment by tianweiy** [comment]
I don't plan to support this in the near future. My current repo seems to have much higher number ...
