### ISSUE TITLE
How to detect bounding boxes at the back of the vehicle?

### ISSUE THREAD

**Issue by vardeep-archive** [tianweiy/CenterPoint-KITTI#28]
This is a dataset/general query.

I have trained an object detector with "centerpoint_rnn.cfg" config and the model has trained and is working well. But I noticed just now that the KITTI dataset has gt bbox information just for objects which are in the FOV of the cameras. So the cars at the back of the vehicle are not detected. This has caused problems for me since I am working on Moving Object Segmentation and I want to detect vehicles that are at the back as well. Any suggestion on how that can be achieved.
![Screenshot from 2021-10-18 12-47-22](https://user-images.githubusercontent.com/87229887/137716887-fc49120e-ef49-4b7c-9a9e-05135d1517e5.png)
In the image, it can be seen that  the cars in front of the vehicle bearing laser scanner are detected but there is a car just behind the vehicle which remains undetected

**Comment by maayanYa** [comment]
Hi , 
I'm having the same issue but somehow changing the point cloud range didn't effect . 
The detector doesn't recognise the objects in the right part of the point cloud and even when I change the point cloud range and make sure the point coordinates are inside the point cloud range - objects there are still not detected at all.

And I also noticed that not every number there is accepted, some cause bugs , didn't understand yet what causes it .

Did you change anything else other than the point cloud range ? 


Thank you !
