### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'

### ISSUE THREAD

**Issue by ChunmianLin** [tianweiy/CenterPoint-KITTI#3]
Hi, I followed the installation and get_start files to complete necessary running environment, and this bug happened. How should I solve this, and please help me !
Thanks!

**Comment by tianweiy** [comment]
Seems that some value need to be converted to cuda. You can just add a cuda() at that line ?

**Comment by tianweiy** [comment]
I mean adding a cuda() to this line you referenced https://github.com/tianweiy/CenterPoint-KITTI/issues/2#issuecomment-847645049

Does this work? If not please paste the error message, this is easier than sentences for debugging

**Comment by ChunmianLin** [comment]
> I mean adding a cuda() to this line you referenced [#2 (comment)](https://github.com/tianweiy/CenterPoint-KITTI/issues/2#issuecomment-847645049)
> 
> Does this work? If not please paste the full log, this is easier than sentences for debugging

Thanks. The error information is as follows:
![Screenshot from 2021-05-26 09-06-01](https://user-images.githubusercontent.com/53289159/119587821-10713a00-be02-11eb-97d6-3a7a81c57c9e.png)
Where should cuda() be added?

**Comment by tianweiy** [comment]
either center_int or feature_map_size

**Comment by tianweiy** [comment]
like

center_int[0].cuda() < feature_map_size[0].cuda() ...

**Comment by ChunmianLin** [comment]
> like
> 
> center_int[0].cuda() < feature_map_size[0].cuda() ...

Many thanks. As you said, I have added cuda() behind the variance of 'feature_map_size', and new type problem happens:
![Screenshot from 2021-05-26 09-17-04](https://user-images.githubusercontent.com/53289159/119588326-27645c00-be03-11eb-8dda-e69d5fb68ce7.png)
How to solve it? By the way, adding cuda() after center_int, e.g center_int().cuda() does not make effect.

**Comment by tianweiy** [comment]
try this 
```
if not (0 <= center_int[0] < feature_map_size[0].cuda().int()
      and 0 <= center_int[1] < feature_map_size[1].cuda().int()):
```

**Comment by ChunmianLin** [comment]
I convert the type of feature_map_size to int32 by adding .to(torch.int32).
It seems this bug has passed, and the code run normally.
Many thanks for your helps.

**Comment by bi-qiuqiu** [comment]
> I convert the type of feature_map_size to int32 by adding .to(torch.int32). It seems this bug has passed, and the code run normally. Many thanks for your helps.
Did you change all feature_map_size in this file to feature_map_size.to(torch.int32)?I changed line 269 to if not (0 <= center_int[0] < feature_map_size[0].cuda().int()，but this problem arises.
      and 0 <= center_int[1] < feature_map_size[1].cuda().int()):
![image](https://user-images.githubusercontent.com/76415164/157229663-d7bb0841-0c39-4429-b6d0-705c17a23974.png)
