### ISSUE TITLE
How can I get the kitti test set's labels?

### ISSUE THREAD

**Issue by kewosihuzuobudao** [tianweiy/CenterPoint-KITTI#30]
I find the kitti test set's labels in many ways.But I cannot get this.

**Comment by kewosihuzuobudao** [comment]
Hello author.
I made some modifications to your model. I want to try to test on kitti's test sets. But I can't find the labels of the test sets.
I have seen in many papers other authors use their models to test on kitti's test set. Does you have or do you know where to get it. I am very sorry to disturb you.

**Comment by kewosihuzuobudao** [comment]
Do I need to apply in the kitti official website. In this way can I get the qualification to test on the test set?

**Comment by kewosihuzuobudao** [comment]
Do I need to apply in the kitti official website? In this way I can get the qualification to test on the test set?

**Comment by tianweiy** [comment]
we have no way to get test set label. You need to compute the detection results and submit it to the server and it will return a map number. I suggest to mainly compare on validation set as there is a limit on the number of times you can submit to server

**Comment by kewosihuzuobudao** [comment]
Thank you very much for solving my question.

> we have no way to get test set label. You need to compute the detection results and submit it to the server and it will return a map number. I suggest to mainly compare on validation set as there is a limit on the number of times you can submit to server

Thank you very much for solving my question.
