### ISSUE TITLE
On model robustness

### ISSUE THREAD

**Issue by fyzhong** [tianweiy/CenterPoint-KITTI#34]
I've inferred the Pandset(Waymo) dataset by your KITTI weight, it can't work well.
but can inference the KITTI by cityscape models in 2D.
What are the differences between different point cloud datasets?(except the number of laser lines)

**Comment by tianweiy** [comment]
laser lines are main difference. Then it is the dataset size. Waymo is much larger so model trained on it will be much better than model trained on KITTI. We get Waymo model at https://github.com/tianweiy/CenterPoint

**Comment by fyzhong** [comment]
We tried adding domain adaption in front of the model, and achieved a better result. Thank you for your reply

**Comment by LinyeLi60** [comment]
> We tried adding domain adaption in front of the model, and achieved a better result. Thank you for your reply

Hi, can you share some informations how you add domain adaption? Thank you.
