### ISSUE TITLE
rank of centerpoint on kitti car hard benchmark

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint-KITTI#37]
hi ,nice work! I wonder know the exact rank of centerpoint on [kitti car hard benchmark](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d).

thanks!

**Comment by tianweiy** [comment]
i never train (or submit) a test model. I think it is not competitive on KITTI (100+ for single stage, and 50+ for second stage)
