### ISSUE TITLE
Why there is completely different source code for KITTI dataset?

### ISSUE THREAD

**Issue by AndreasR30** [tianweiy/CenterPoint-KITTI#4]
Could you please explain why you did not extend the original repository for KITTI dataset? I'm not sure which repository to use as I would also like to evaluate on KITTI (besides NuScenes and Waymo).

**Comment by tianweiy** [comment]
The original codebase can do kitti but there need a lot of modification which I don't have time recently

**Comment by tianweiy** [comment]
Please use original codebase for nuScenes and waymo. Kitti is like an additional thing ..

**Comment by XiaoyanQian** [comment]
Hi Tianwei, could I ask what exactly the differences in the code between CenterPoint and CenterPoint-KITTI are? Did it locate on the detection head part?

**Comment by tianweiy** [comment]
there is not much difference (for code). I use two codebase as the old one doesn't have kitti support by default. 

The architecture is slightly different for KITTI / nuscenes / Waymo. (i.e. the RPN is slightly larger for nuScenes / Waymo models)
https://github.com/tianweiy/CenterPoint/blob/37df3425575e44b6e0e6aad76f7f0b90d805d084/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py#L35

https://github.com/tianweiy/CenterPoint/blob/37df3425575e44b6e0e6aad76f7f0b90d805d084/configs/waymo/voxelnet/waymo_centerpoint_voxelnet_1x.py#L28

If you are used to CenterPoint-KITTI model, you can also experiment with the centerpoint baseline in the openpcdet repo https://github.com/open-mmlab/OpenPCDet which uses the same codebase as centerpoint-kitti and also supports nuscenes / waymo datasets

**Comment by XiaoyanQian** [comment]
Thank you so much
