### ISSUE TITLE
about the test on tracking in this project

### ISSUE THREAD

**Issue by FreemanGong** [tianweiy/CenterPoint-KITTI#41]
Hello! Thanks for your projects! I would like to ask if this project have the test of tracking on KITTI dataset.
I can't find the code named tracking in tools. 
How can I run this project and get the effect of tracking.
Looking forward to your reply!

**Comment by tianweiy** [comment]
no, there is no tracking

**Comment by raikaland** [comment]
how can i complement the tracking on kitti?

**Comment by yaobaishen** [comment]
Is there any complementary project to add tracking on KITTI?
