### ISSUE TITLE
dist.init_process_group hangs

### ISSUE THREAD

**Issue by shawnding** [tianweiy/CenterPoint-KITTI#49]
Hi,

I'm trying to train CenterPoint on KITTI. Single GPU training is fine, but 4-GPU training hangs at this line: 
https://github.com/tianweiy/CenterPoint-KITTI/blob/df2b099c057686aec832a55046c272108e310e2f/pcdet/utils/common_utils.py#L147-L152

I'm using a nccl backend, tcp_port is free.

Any help would be appreciated!

**Comment by tianweiy** [comment]
comment out those few lines ? 

See https://github.com/open-mmlab/OpenPCDet/blob/e948c537858d4e468a9ef50b023324f6bc96db2a/pcdet/utils/common_utils.py#L181

**Comment by shawnding** [comment]
It worked! Thanks for the quick reply!
