### ISSUE TITLE
Question about CenterPoint's model

### ISSUE THREAD

**Issue by ZhangYu1ing** [tianweiy/CenterPoint-KITTI#8]
Hi,

sorry to bother you. Regarding the model of CenterPoint, I have the following questions:

1. Which is the first network layer for CenterPoint? In my opinion, the first layer of CenterPoint network may be the MeanVFE, correct?

2. What is the input and output of the first layer network？What is the size of its input? Could you please point out where is it defined?

Thank you so much.

**Comment by tianweiy** [comment]
1. Yes
2. See this for the size of the input https://github.com/tianweiy/CenterPoint-KITTI/blob/ef36fcee7b2773600590f9283cc7271ede50c389/pcdet/models/backbones_3d/vfe/mean_vfe.py#L18 
I think it is generated here https://github.com/tianweiy/CenterPoint-KITTI/blob/ef36fcee7b2773600590f9283cc7271ede50c389/pcdet/datasets/processor/data_processor.py#L62

**Comment by yaxi333** [comment]
Hi,  @tianweiy 

Thanks for your reply! 

1.I want to ask how many neurons do the first layer has then? I mean how many neurons are the first layer connected to the second layer? 

2. And the second layer is Backbone3d: VoxelBackBone8x right? And the second layer seems to have 16 neurons after I print the model on the monitor.  But where did you assign this?

Thanks in advance!

**Comment by tianweiy** [comment]
1. first layer is voxelization. It is just simple average and doesn't have learnable weights. 

2. first learnable layer is defined here https://github.com/tianweiy/CenterPoint-KITTI/blob/ef36fcee7b2773600590f9283cc7271ede50c389/pcdet/models/backbones_3d/spconv_backbone.py#L76
